### ISSUE TITLE
Public repository?

### ISSUE THREAD

**Issue by evrardjp** [citynetwork/Erinan-om-tystnadsplikt#1]
Hello @kimhindart . This seems related to our internal procedures for Sweden, why is this a public repo?

**Comment by kimhindart** [comment]
our code of conduct is intentionally public for customer to review and it is great for potential employees to review before they have internal access to City resources.

**Comment by evrardjp** [comment]
Great idea. Would it make sense to include this in our documentation efforts instead?
For me, we would reduce the amount of places where we manage the information.
